version: '3'
services:
    mysql:
        image: mysql:8.0
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev-ticketing # 최초 생성되는 기본 DB
            MYSQL_USER: user
            MYSQL_PASSWORD: 1234
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./initdb:/docker-entrypoint-initdb.d/ # 초기화 스크립트
        command: --default-authentication-plugin=mysql_native_password
    adminer:
        image: adminer
        restart: always
        ports:
            - "18080:8080"

volumes:
    mysql_data:
