spring:
    config:
        activate:
            on-profile: dev
    security:
        user:
            name: user
            password: 1111

    datasource:
        url: "jdbc:mysql://localhost:3306/dev-ticketing"
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: user
        password: 1234

    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                default_batch_fetch_size: 50000

#    kafka:
#        bootstrap-servers: localhost:9092
#        producer:
#            acks: all
#        consumer:
#            group-id: group_id
#            auto-offset-reset: earliest
#        admin:
#            auto-create: true