server:
    servlet:
        encoding:
            force-response: true

spring:
    config:
        activate:
            on-profile: test

    datasource:
        url: "jdbc:mysql://localhost:3306/test_ticketing"
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: user
        password: 1234

    jpa:
        database: mysql
        hibernate:
            ddl-auto: none
        show-sql: false

#    kafka:
#        bootstrap-servers: localhost:9092
#        producer:
#            acks: all
#        consumer:
#            group-id: group_id
#            auto-offset-reset: earliest
#        admin:
#            auto-create: true