server:
    port: 80

spring:
    application:
        name: ticketing
    profiles:
        active: dev
        group:
            test: test
            dev: dev

logging:
    level:
        org.springframework: error
        org.hibernate.SQL: DEBUG